### ISSUE TITLE
Auto shelve once per workspace per user

### ISSUE THREAD

**Issue by icnocop** [vercellone/tfsautoshelve#12]
Hi.

Thank you for TFS Auto Shelve.

I would like to request that if I have multiple Visual Studio solutions open that point to the same workspace that only one shelvset is shelved per interval.

Currently if I have multiple Visual Studio solutions open that point to the same workspace, a shelveset is created multiple times per interval which is unexpected.

Thank you.

**Comment by vercellone** [comment]
I explored this feature last year, but ultimately abandoned it.  The benefit didn't justify the added complexity.

Also...it shouldn't be creating _redundant_ shelvesets.  I implemented delta detection for VS 2013+, which should suppress the secondary instances from shelving identical changes.  If the delta detection is broken and the shelvesets are redundant please open another issue with steps to reproduce.

**Comment by vercellone** [comment]
I was able to reproduce redundant shelvesets across multiple VS instances.  I created Issue #14 to address the faulty delta detection.  

Also: Stay tuned for a possible commit that includes your requested enhancement after all.

**Comment by vercellone** [comment]
Won't fix.
