### ISSUE TITLE
"Pause while debugging" confusion

### ISSUE THREAD

**Issue by icnocop** [vercellone/tfsautoshelve#13]
I'm confused with the option "Pause while debugging"

The option indicates: 

> If False, Auto Shelve will pause while debugging  

but shouldn't it read 

> If **True**, Auto Shelve will pause while debugging"

?

Thank you.

![tfs autoshelve](https://cloud.githubusercontent.com/assets/507649/10408176/910b2006-6eab-11e5-8c85-9e4d614e0b3a.GIF)

**Comment by vercellone** [comment]
You can install the latest vsix from [AppVeyor](https://ci.appveyor.com/project/vercellone/tfsautoshelve/build/5.1.16/artifacts).

I won't publish this change alone to the visual studio gallery.  It will be included in future versions.
