### ISSUE TITLE
On install: Prerequisite cannot be resolved

### ISSUE THREAD

**Issue by xrmedge** [vercellone/tfsautoshelve#18]
Hi,
I have been using AutoShelve successfully on VS 2015 for a while now and I really like it.

I just installed Visual Studio 2017 Community and am trying to load TFS Auto Shelve for VS 2017. I'm getting the below error:
![2017-03-07_14-11-50](https://cloud.githubusercontent.com/assets/13258311/23673372/1155c34a-0340-11e7-9b6c-5f128da95ab9.jpg)

I looked at the VSIX file and it appears that there are 3 prerequisites:

1. Visual Studio core editor
2. Profiling tools
3. IntelliTrace

I think I have the Studio core editor and Profiling tools, but it appears that IntelliTrace is available only in VS Enterprise.

Any thoughts about how to get around this?

Thanks,
A.F.

**Comment by vercellone** [comment]
Hi A.F.

I'm glad you've found the extension useful.

This Intellitrace PreRequisite is likely just an oversight on my part.  I was originally targeting Enterprise only for other reasons.  I'll verify Intellitrace is unnecessary and remove it or explain why it is necessary ASAP.  If I can't complete the change tomorrow (Thursday) I'll at least post an updated ETC.

-Jason

**Comment by vercellone** [comment]
I added Microsoft.VisualStudio.Pro as an install target as well, but visualstudiogallery isn't recognizing it for reasons unknown.
