### ISSUE TITLE
Feature request: Shelve before undo

### ISSUE THREAD

**Issue by weitzhandler** [vercellone/tfsautoshelve#19]
Any call for _Undo Pending Changes_ should incur in a shelve made before it.

Thank you!

**Comment by icnocop** [comment]
Note that this may cause Visual Studio to prompt you to reload projects or solutions if they're open in the IDE because it detects that they've changed on disk.  This wouldn't be the best experience if you're in the middle of typing.

**Comment by vercellone** [comment]
In the meantime, you should take advantage of the Team->TFS Auto Shelve Now menu action (bound to the Ctrl+T keyboard shortcut by default).
