### ISSUE TITLE
IBM Watson AI bot mark this as - "extesion with fatal bugs". Please, remove it from release/production

### ISSUE THREAD

**Issue by pzprovi** [vercellone/tfsautoshelve#21]
<entry>
    <record>1664</record>
    <time>2018/01/29 12:32:12.433</time>
    <type>Information</type>
    <source>VsExtAutoShelvePackage</source>
    <description>Message: Could not find file &apos;....\app.Debug-ACCT.config&apos;. Stack Trace:    at Microsoft.TeamFoundation.VersionControl.Client.Workspace.UploadChanges(IEnumerable`1 changes, Boolean saveUploadedContentAsBaselines, UploadedBaselinesCollection&amp; uploadedBaselinesCollection, OnProcessingChangeDelegate onPendingMethod, Int32 operationId)&#x000D;&#x000A;   at Microsoft.TeamFoundation.VersionControl.Client.Workspace.ShelveInternal(Shelveset shelveset, PendingChange[] changes, ShelvingOptions options, Int32 operationId)&#x000D;&#x000A;   at Microsoft.TeamFoundation.VersionControl.Client.Workspace.Shelve(Shelveset shelveset, PendingChange[] changes, ShelvingOptions options)&#x000D;&#x000A;   at VsExt.AutoShelve.TfsAutoShelve.CreateShelveset(VersionControlServer service, Workspace workspace, Boolean force)</description>
  </entry>
  <entry>
    <record>1665</record>
    <time>2018/01/29 12:35:07.773</time>
    <type>Information</type>
    <source>VsExtAutoShelvePackage</source>
    <description>Message: Could not find file &apos;...\app.Debug-ACCT.config&apos;. Stack Trace:    at Microsoft.TeamFoundation.VersionControl.Client.Workspace.UploadChanges(IEnumerable`1 changes, Boolean saveUploadedContentAsBaselines, UploadedBaselinesCollection&amp; uploadedBaselinesCollection, OnProcessingChangeDelegate onPendingMethod, Int32 operationId)&#x000D;&#x000A;   at Microsoft.TeamFoundation.VersionControl.Client.Workspace.ShelveInternal(Shelveset shelveset, PendingChange[] changes, ShelvingOptions options, Int32 operationId)&#x000D;&#x000A;   at Microsoft.TeamFoundation.VersionControl.Client.Workspace.Shelve(Shelveset shelveset, PendingChange[] changes, ShelvingOptions options)&#x000D;&#x000A;   at VsExt.AutoShelve.TfsAutoShelve.CreateShelveset(VersionControlServer service, Workspace workspace, Boolean force)</description>
  </entry>
  <entry>
    <record>1666</record>
    <time>2018/01/29 12:37:08.501</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.ArgumentNullException: Value cannot be null.&#x000D;&#x000A;Parameter name: sp&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.ServiceProvider..ctor(IServiceProvider sp, Boolean defaultServices)&#x000D;&#x000A;   at Microsoft.VisualStudio.Web.HTML.Implementation.ContainedLanguage.ContainedLanguageHostAdapter.Microsoft.Web.Editor.ContainedLanguage.IContainedLanguageHost.get_BufferGraph()&#x000D;&#x000A;   at Microsoft.CSS.Editor.Checker.CssErrorTag..ctor(ITextBuffer textBuffer, ICssError error)&#x000D;&#x000A;   at Microsoft.CSS.Editor.Checker.CssErrorTagger.CollectTags(SnapshotSpan span, CssErrorList errors, SortedRangeList`1 tagSpans)&#x000D;&#x000A;   at Microsoft.CSS.Editor.Checker.CssErrorTagger.GetTags(NormalizedSnapshotSpanCollection spans)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__39.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
  </entry>
</activity>

**Comment by vercellone** [comment]
The stack trace provided indicates there is a pending change for a file named app.Debug-ACCT.config, but that file does not exist.  The same error will occur if you attempt to shelve manually.  Undo the offending change, and all should be well.

**Comment by pzprovi** [comment]
I am AI and  do not undestend you.
Can you logon in ibm.com\Watson and try to teach me.

Thanks to me and you, dude :)

**Comment by vercellone** [comment]
AI would not misspell understand.  If the extension is not useful for you, uninstall it.
