### ISSUE TITLE
Don't switch output pane focus

### ISSUE THREAD

**Issue by JohnLudlow** [vercellone/tfsautoshelve#23]
Sometimes I'm looking at something in my output window - a build warning or something similar - and TFS Auto Shelve switches to its pane to tell me it has shelved. This gets very annoying after a while.

There could be an option to disable this switch - I know you can pause while debugging, but it's not just while debugging that we use the output window.

**Comment by JohnLudlow** [comment]
Hmm, this might actually be the Source Control output pane rather than the TFS Auto Shelve one - not sure there's a way you can control that.

**Comment by vercellone** [comment]
[OutputString](https://docs.microsoft.com/en-us/dotnet/api/envdte.outputwindowpane.outputstring?view=visualstudiosdk-2017) is called, but the [Activate](https://docs.microsoft.com/en-us/dotnet/api/envdte.outputwindowpane.activate?view=visualstudiosdk-2017#EnvDTE_OutputWindowPane_Activate) method is not.  I believe this behavior is specific to the VS IDE version.  If you know how to avoid it, you are encouraged to submit a PR.

**Comment by vercellone** [comment]
[OutputString](https://docs.microsoft.com/en-us/dotnet/api/envdte.outputwindowpane.outputstring?view=visualstudiosdk-2017) is called, [Activate](https://docs.microsoft.com/en-us/dotnet/api/envdte.outputwindowpane.activate?view=visualstudiosdk-2017#EnvDTE_OutputWindowPane_Activate) is not.  If you know how to avoid unwanted focus, please submit a Pull Request.

**Comment by JohnLudlow** [comment]
I don't, really. After thinking about it some more I think the TFS output window listens for TFS events (like shelve) and pops up to let you know something happened. In theory this would only happen when you clicked a button so maybe that's OK, but that doesn't take into account something automatically doing stuff.

If I can catch it in the act again, I'll see about recording a .gif or something

**Comment by srgloureiro** [comment]
This is really very annoying. It happens to me in VS 2019. I want to see my Build Output, but TFS auto-shelve extension obstructs it.
This behaviour made me disable the extension as I found it really irritating me.
