### ISSUE TITLE
Will this be updated for VS 2019?

### ISSUE THREAD

**Issue by e128** [vercellone/tfsautoshelve#25]
I love the auto-shelve extension. Are there plans to get one for VS 2019 that's around the corner?

**Comment by vercellone** [comment]
Eventually.  But, probably not soon, as I am not actively using TFSVC.

**Comment by erikread** [comment]
I too would love for this to upgraded for VS 2019

**Comment by vercellone** [comment]
Please try [TFSAutoShelve.7.0.vsix](https://ci.appveyor.com/api/buildjobs/dqr8s4rs874byaws/artifacts/VsExt.AutoShelve%2Fbin%2FPackage%2FTfsAutoShelve.7.0.vsix).  Feedback (positive or negative) would be greatly appreciated!

**Comment by e128** [comment]
Installed and testing now. First auto-shelve worked. :) Thanks!

**Comment by Bolli1983** [comment]
Auto-shelving works fine, however Visual Studio now regularly crashes after you close it with the following exception (taken from the eventlog)

System.ObjectDisposedException
   bei System.Threading.ThreadLocal`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetValueSlow()
   bei System.Threading.ThreadLocal`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Value()
   bei Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   bei Microsoft.VisualStudio.Shell.AsyncPackage.Dispose(Boolean)
   bei VsExt.AutoShelve.VsExtAutoShelvePackage.Dispose(Boolean)
   bei VsExt.AutoShelve.VsExtAutoShelvePackage.Finalize()

**Comment by erikread** [comment]
Installed this morning. Will let you know.

**Comment by erikread** [comment]
FYI, this has been working great. Been running since July 10

**Comment by joltcoder** [comment]
Just installed... so far so good.

**Comment by JonathanDCrowe** [comment]
The build has been working successfully in our environment with VS2019. I would really like to see this officially released to the marketplace.

**Comment by vercellone** [comment]
https://marketplace.visualstudio.com/items?itemName=Vercellone.TFSAutoShelveforVisualStudio

**Comment by Bolli1983** [comment]
The issue I posted above seems to be fixed, thank you very much!
